#!/usr/bin/env bash

# I found this handy way to delete the shortest match of a substring from the end of a string:
# ${string%substring}

# Take the full path, subtract the name of this script (treasure_server), then append /src/main.py and run
${0%treasure_server}/src/server.py
