terrain = [
"                   XXX   X      ",
"                 X XXX X X XXXX ",
" X   X           X   X X X X    ",
"   X    X        XXX X X X X XXX",
"       X         X   X X X X    ",
"X X  X           X XXX X X XXXX ",
"          X      X     X   X    ",
"   X       X     XXXXXXXX XX XXX",
"         XXXX           X X     ",
"           X            X X     ",
"XXXX X    X                     ",
"      XX    XXX  XXX  X X  XXX  ",
"XXXX X        X  X X  X X  X    ",
"            XXX  X X  XXX  XXX  ",
"                                ",
"                                ",
"     XXXXXXXXXXXX XXXXX         ",
"     X          X     X         ",
"     X    X     X     X         ",
"     X    X           X         ",
"     X XXXX XXXXXXXXXXX    XXXXX",
"                                ",
"   XXXX                  XXXXX  ",
"XXXX                     X      ",
"     X XXXX        X X   X      ",
" XXXXX    X       XX XX  XX   XX",
"     XXXX X      XXX XXX  X     ",
"XXXX XX   X     XXXX XXXX X     ",
"   X XX XXXXXXX    X X    X     ",
" X      X                XXXXX  ",
"  XXXXXXXXXX XXXXXXXX    X      ",
"X                        X      ",
]

