terrain = [
"    X      XXXXX            X   ",
"    X XXXX X   XXX XXX    X   X ",
"      X    X X X     XXXXXX XXX ",
" XXXXXX XX   X   XXX        X   ",
"         XXXXX XXX XXXXX    X XX",
"XXXX X                 X        ",
"     XXXXXX XXXXXX XX  X XXXXXX ",
" XXX  X          X X     X    X ",
" X    X XXXXXXXX X XXXXX X XX   ",
"   XX   X   X    X X     X  XXXX",
"XXXX  XXX X X XX X X XXXXXX     ",
"     XX   X   X  X X      XXX XX",
" XXXXX  XXXXX XX X XXXXXX     X ",
"       XX        X    X XXXXX X ",
"XXX XXXX  X XXXXXXXXX X     X   ",
"          X      X    X XXXXX   ",
"XXXXXXXX  XXXXX               XX",
"          X                     ",
"                XXXXXXX         ",
"                      X         ",
"          XXXXXXXXXXX X         ",
"          X           X         ",
"          X XXXXXXXXXXX         ",
"          X           X         ",
"XXXXXXXXX X XXXXXXXXX X XXXXXXXX",
"          X           X         ",
" XXXXXXXXXXXXXXX XXXXXXXXXXXXXX ",
"                                ",
"XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX",
"                                ",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ",
"                                ",
]

